title: <p align="center"> Ariful Islam Arif </p>

logo: "/images/logo.png?raw=true"

description:
  <p align="center", color="black">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ariful-islam-arif-2987b51a3/">LinkedIn</a> |
  <a href="https://github.com/arifulmrislam">GitHub</a>
  </p>
  
  <p align="justify">
  I have a BS.c degree in Electrical and Electronics Engineering at Daffodil International University.
  <br><br>
  I am currently an Automation and IoT Engineer at Polisea S.A with a focus on IoT, IIoT & Cloud Computing Solutions.
  <br><br>
  </p>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-215702301-1 # Google Analytics tracking ID

